src/Entity/Video.php
<?php

namespace App\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\VideoRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=VideoRepository::class)
 */
class Video
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $video;

    /**
     * @Assert\NotBlank(message="Le titre ne peut pas être vide.")
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $content;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $last_update_date;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $publication_date;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $isPublished;

    /**
     * @ORM\ManyToMany(targetEntity=Category::class, inversedBy="Videos")
     */
    private $categories;




    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->publication_date = new \DateTime;
        $this->isPublished = false;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getVideo(): ?string
    {
        return $this->video;
    }

    public function setVideo(?string $video): self
    {
        $this->video = $video;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }


    public function getLastUpdateDate(): ?\DateTimeInterface
    {
        return $this->last_update_date;
    }

    public function setLastUpdateDate(?\DateTimeInterface $last_update_date): self
    {
        $this->last_update_date = $last_update_date;

        return $this;
    }

    public function getPublicationDate(): ?\DateTimeInterface
    {
        return $this->publication_date;
    }

    public function setpublicationDate(?\DateTimeInterface $publication_date): self
    {
        $this->publication_date = $publication_date;

        return $this;
    }

    public function getIsPublished(): ?bool
    {
        return $this->isPublished;
    }

    public function setIsPublished(bool $isPublished): self
    {
        $this->isPublished = $isPublished;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        $this->categories->removeElement($category);

        return $this;
    }

    public function isIsPublished(): ?bool
    {
        return $this->isPublished;
    }



}

templates/add.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ parent() }} | Ajouter un article{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col s12 m12 l12">
                <h4>Ajout d'un article</h4>
            </div>
        </div>
        {% include "includes/article_form.html.twig" %}
    </div>
{% endblock %}

templates/base.html.twig
{# templates/base.html.twig #}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}7355608{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% block stylesheets %}
       <link rel="stylesheet" type="text/css" href="{{ asset('asset/css/materialize.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ asset('asset/css/app.css') }}">
    {% endblock %}
</head>
<body>
    <nav>       
        <div class="nav-wrapper">
            <div class="container">
                <a href="{{ path('homepage') }}" class="brand-logo">Accueil</a>
                <a href="{{ path('page_news') }}" class="brand-logo">News</a>
                <a href="{{ path('video_index') }}" class="brand-logo">Videos</a>
                <a href="{{ path('contact_add') }}" class="brand-logo">Contact</a>
                      <ul id="nav-mobile" class="right hide-on-med-and-down">
                    {% if app.user %}
                        {% if is_granted('ROLE_ADMIN') %}
                            <li><a href="{{ path('admin') }}">Admin</a></li>
                        {% endif %}
                        
                        <li><a href="{{ path('app_logout') }}">Déconnexion</a></li>
                    {% else %}
                        <li><a href="{{ path('app_register') }}">Incription</a></li>
                        <li><a href="{{ path('app_login') }}">Connexion</a></li>
                        {% endif %}
                        
                  </ul>
            </div>
        </div>
      </nav>

      {% block content %}

      {% endblock %}

    {% block scripts %}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    {% endblock %}
</body>
</html>

templates/contact_add.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ parent() }} | Ajouter un commentaire{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col s12 m12 l12">
                <h4>Ajout d'un commentaire</h4>
            </div>
        </div>
        {% include "includes/contact_form.html.twig" %}
    </div>
{% endblock %}

templates/contact_index.html.twig
{% extends "base.html.twig" %}

{% block title %}Accueil commentaires| {{ parent() }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            {% for contact in contacts %}
                <div class="col s12 m4 l3">
                    <div class="article-card10">
                        {{ contact.username }}
                        <span class="date">{{ contact.publicationDate|date('d/m/Y') }}</span>       
                    </div>
                    <div class="contact-content">{{ contact.content }}</div>
                        <h2></h2>
                    
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/contact_show.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ Commentaire }}{% endblock %}

{% block content %}
    <article class="container">
        <div class="row">
            <div class="col s12 m12 l8 offset-l2">
                <h1>{{ contact.username }}</h1>
            </div>
        </div>
        <div class="row">
            <div class="col s12 m12 l8 offset-l2">
                <p>
                    {{ contact.content }}
                </p>
            </div>
    </article>
{% endblock %}

                        

templates/edit.html.twig
{% extends "base.html.twig" %}

{% block title %}Modifier{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col s12 m12 l12">
                <h4>Modifier l'article {{ article.title }}</h4>
                {% if article.picture is not null %}
                    <img width="300" src="{{ asset('uploads/' ~ article.picture) }}">
                {% endif %}
            </div>
        </div>
        {% include "includes/article_form.html.twig" %}
    </div>
{% endblock %}

templates/index.html.twig
{% extends "base.html.twig" %}

{% block title %}Accueil | {{ parent() }}{% endblock %}

{% block content %}
<div class="container1">
        <div class="row1">
            {% for video in videos %}
                <div class="col s12 m4 l3">
                    <div class="article-card">
                    <a href="{{ path('video_show', {'id': video.id}) }}">
                        <embed src="{{ asset('uploads/videos/' ~ video.video) }}" autostart="false" height="300" width="300" /></embed>
                        {{ video.title }}
                        <span class="date">{{ video.publicationDate|date('d/m/Y') }}</span>
                        <h2></a></h2>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="container2">
        <div class="row2">
            {% for article in articles %}
                <div class="col s12 m4 l3">
                    <div class="article-card">
                    <a href="{{ path('article_show', {'id': article.id}) }}">
                        <img src="{{ asset('uploads/' ~ article.picture) }}" class="responsive-img">
                        {{ article.title }}
                        <h2></a></h2>
                        <span class="date">{{ article.publicationDate|date('d/m/Y') }}</span>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/match.html.twig
{% extends "base.html.twig" %}

templates/news.html.twig
{% extends "base.html.twig" %}

{% block title %}Articles | {{ parent() }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            {% for article in articles %}
                <div class="col s12 m4 l3">
                    <div class="article-card">
                    <a href="{{ path('article_show', {'id': article.id}) }}">
                        <img src="{{ asset('uploads/' ~ article.picture) }}" class="responsive-img">
                        {{ article.title }}
                        <h2></a></h2>
                        <span class="date">{{ article.publicationDate|date('d/m/Y') }}</span>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/show.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ article.title }}{% endblock %}

{% block content %}

    <article class="container">
        <div class="row">
            <div class="col s12 m12 l8 offset-l2">
                <h1>{{ article.title }}</h1>
                <img src="{{ asset('uploads/' ~ article.picture) }}" class="responsive-img">
                <p>
                <small>
                    {% for category in article.categories %}
                        <a href="">{{ category.label }}</a>
                    {% endfor %}
                </small>
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col s12 m12 l8 offset-l2">
                <p>
                    {{ article.content }}
                </p>
                <div class="fb-share-button" data-href="http://r301.antivackis.com/index.php/show/%7B%7B article.id }}" data-layout="button" data-size="small">
                        <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fr301.antivackis.com%2Findex.php%2Fshow%2F%257B%257B+article.id+%257D%257D&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Share on facebook</a></div>
                    <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            </div>
    </article>
{% endblock %}

templates/video_add.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ parent() }} | Ajouter une vidéo{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col s12 m12 l12">
                <h4>Ajout d'une vidéo</h4>
            </div>
        </div>
        {% include "includes/video_form.html.twig" %}
    </div>
{% endblock %}

templates/video_edit.html.twig
{% extends "base.html.twig" %}

{% block title %}Modifier{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col s12 m12 l12">
                <h4>Modifier la vidéo {{ video.title }}</h4>
                {% if video.video is not null %}
                    <embed src="{{ asset('uploads/videos/' ~ video.video) }}" autostart="false" height="300" width="300" /></embed>
                {% endif %}
            </div>
        </div>
        {% include "includes/video_form.html.twig" %}
    </div>
{% endblock %}

templates/video_index.html.twig
{% extends "base.html.twig" %}

{% block title %}Accueil vidéos| {{ parent() }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            {% for video in videos %}
                <div class="col s12 m4 l3">
                    <div class="article-card">
                    <a href="{{ path('video_show', {'id': video.id}) }}">
                        <embed src="{{ asset('uploads/videos/' ~ video.video) }}" autostart="false" height="300" width="300" /></embed>
                        {{ video.title }}
                        <span class="date">{{ video.publicationDate|date('d/m/Y') }}</span>
                        <h2></a></h2>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/video_show.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ video.title }}{% endblock %}

{% block content %}
    <article class="container">
        <div class="row">
            <div class="col s12 m12 l8 offset-l2">
                <h1>{{ video.title }}</h1>
                <embed src="{{ asset('uploads/videos/' ~ video.video) }}" autostart="false" height="300" width="300" /></embed>
            </div>
        </div>
        <div class="row">
            <div class="col s12 m12 l8 offset-l2">
                <p>
                    {{ video.content }}
                </p>
            </div>
    </article>
{% endblock %}

                        